version: "3"
services:
  nginx:
    image: nginx
    container_name: bookslib_nginx
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/logs/:/var/log/nginx_log/
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php-fpm
      - db
    networks:
      - net
  php-fpm:
    build: docker/php-fpm
    container_name: bookslib_php-fpm
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/logs/:/var/log/php/
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - db
    networks:
      - net
  db:
    image: postgres:12
    container_name: bookslib_db
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_ROOT_USER}"
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    networks:
      - net
  redis:
    image: redis
    container_name: bookslib_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - net
networks:
  net:
    driver: bridge