controllers:
    resource: ../../src/App/Controller/
    type: annotation

api-controllers:
    resource: ../../src/Api/Controller/BookController.php
    type: annotation

kernel:
    resource: ../../src/App/Kernel.php
    type: annotation
